org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.87
neo_version_range=[26.2,26.3)
moddevgradle_version=2.0.147

sodium_version=mc26.2-0.9.2-neoforge
sodium_api_version=0.9.2+mc26.2
sodium_version_range=[0.9.2,)
iris_version=1.11.2+26.2-neoforge
lithium_version=mc26.2-0.25.3-neoforge
vivecraft_version=26.2-1.3.15-neoforge

lwjgl_version=3.4.1

mod_version=0.2.20-beta
maven_group=me.cortex
archives_base_name=voxy
mod_id=voxy
mod_name=Voxy
mod_license=All-Rights-Reserved
