# Gradle JVM args
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.172

# Parchment mappings
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Mod
mod_id=voxy
mod_version=0.1.0-alpha
maven_group=me.cortex
archives_base_name=voxy-neoforge