# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon = false

# NeoForge Properties
minecraft_version=1.21.1
neoforge_version=21.1.233
neogradle_version=7.0.163


# Mod Properties
mod_version = 0.2.0-alpha-neoforge
maven_group = io.github.eyecrasher07
archives_base_name = neovoxy
