modLoader="javafml"
loaderVersion="[4,)"
license="All-Rights-Reserved"
issueTrackerURL="https://github.com/MCRcortex/voxy/issues"

[[mods]]
modId="voxy"
version="${version}"
displayName="Voxy"
description="Far distance rendering mod utilising LoDs"
authors="Cortex"
logoFile="assets/voxy/icon.png"

[[dependencies.voxy]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="sodium"
type="required"
versionRange="[0.8,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="client.voxy.mixins.json"

[[mixins]]
config="common.voxy.mixins.json"
