modLoader="javafml"
loaderVersion="[4,)"
license="All-Rights-Reserved"
issueTrackerURL="https://github.com/EyeCrasher07/NeoVoxy/issues"
[[mods]]
modId="neovoxy"
version="${version}"
displayName="NeoVoxy"
displayURL="https://github.com/EyeCrasher07/NeoVoxy"
description="Unofficial NeoForge port of Voxy / NeoVoxy for far-distance LoD rendering. Not official and not supported by the original developer."
authors="EyeCrasher"
credits="Original Voxy / NeoVoxy by Cortex / MCRcortex. Unofficial NeoForge port by EyeCrasher. Not official and not supported by Cortex / MCRcortex."
logoFile="assets/neovoxy/icon.png"

[[dependencies.neovoxy]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.neovoxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.neovoxy]]
modId="sodium"
type="required"
versionRange="[0.8,0.9)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="client.neovoxy.mixins.json"

[[mixins]]
config="common.neovoxy.mixins.json"
