#version 460 core
layout(local_size_x=1, local_size_y=1) in;


layout(binding = 0, std430) restrict buffer DrawCmd {
    uint  count;
    uint  instanceCount;
    uint  firstIndex;
    int  baseVertex;
    uint  baseInstance;
};

layout(binding = 1, std430) restrict buffer NodeList {
    uint nodeCount;
    uint nodes[];
};

void main() {
    count = 6 * 2 * 3;
    instanceCount = nodeCount;
    firstIndex = (1<<8)*6;
    baseVertex = 0;
    baseInstance = 0;
}