#define SCENE_UNIFORM_INDEX 0
#define NODE_DATA_INDEX 1
#define NODE_QUEUE_INDEX 2
#define REQUEST_QUEUE_INDEX 3
#define RENDER_QUEUE_INDEX 4
#define TRANSFORM_ARRAY_INDEX 5
#define NEXT_NODE_QUEUE_INDEX 6

//Samplers
#define HIZ_BINDING_INDEX 0

