modLoader="javafml"
loaderVersion="[0,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Cortex, not-oshi (NeoForge 26.2 port)"
description='''Far distance rendering mod utilising LoDs.'''
logoFile="assets/voxy/icon.png"
displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="common.voxy.mixins.json"

[[mixins]]
config="client.voxy.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sodium"
type="required"
versionRange="${sodium_version_range}"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="iris"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="lithium"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="vivecraft"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"

[modproperties.${mod_id}]
commit="${commit}"
buildtime="${buildtime}"
"sodium:config_api_user"="me.cortex.voxy.client.config.VoxyConfigMenu"
